# Generated by Django 5.2.4 on 2025-07-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='catgeory',
            new_name='category',
        ),
    ]
